apiVersion: kibana.k8s.elastic.co/v1
kind: Kibana
metadata:
  name: observability
  namespace: elastic-monitoring
spec:
  version: 7.9.1
  count: 1
  podTemplate:
    metadata:
      labels:
        app: kibana
        scrape: kb
    spec:
      containers:
      - name: kibana
        resources:
          limits:
            memory: 1Gi
            cpu: 1
  elasticsearchRef:
    name: observability
  config:
    logging:
      json: false
      quiet: true
    xpack.monitoring:
      kibana.collection.enabled: false
      collection.enabled: true
  http:
    service:
      spec:
        type: LoadBalancer
