filebeatConfig:
  filebeat.yml: |
    setup.template.settings:
      index.mapping.total_fields.limit: 10000

    filebeat.autodiscover:
     providers:
       - type: kubernetes
         host: ${NODE_NAME}
         hints.enabled: true

    processors:
      - add_cloud_metadata:
      - add_host_metadata:
      - add_docker_metadata:
      - add_kubernetes_metadata:

    output.logstash:
      hosts: [ "proxy-logstash.elastic-monitoring.svc.cluster.local:5044" ]

    logging.metrics.enabled: false

extraEnvs:
  - name: NODE_NAME
    valueFrom:
      fieldRef:
        fieldPath: spec.nodeName
