extraEnvs:
  - name: LOGGING_ELASTIC_CLOUD_ID
    valueFrom:
      secretKeyRef:
        name: logging-cloud-secret
        key: cloud-id
  - name: LOGGING_ELASTIC_CLOUD_AUTH
    valueFrom:
      secretKeyRef:
        name: logging-cloud-secret
        key: cloud-auth
  - name: LOGGING_ELASTIC_CLOUD_UUID
    valueFrom:
      secretKeyRef:
        name: logging-cloud-secret
        key: cluster-uuid

filebeatConfig:
  filebeat.yml: |
    setup.template.settings:
      index.mapping.total_fields.limit: 10000

    filebeat.autodiscover:
     providers:
       - type: kubernetes
         host: ${NODE_NAME}
         hints.enabled: true

    processors:
      - add_cloud_metadata:
      - add_host_metadata:
      - add_docker_metadata:
      - add_kubernetes_metadata:

    output.logstash:
      hosts: [ "proxy-logstash.elastic-monitoring.svc.cluster.local:5044" ]

    logging.level: warning

    monitoring:
      enabled: true
      cluster_uuid: "${LOGGING_ELASTIC_CLOUD_UUID}"
      cloud.id: "${LOGGING_ELASTIC_CLOUD_ID}"
      cloud.auth: "${LOGGING_ELASTIC_CLOUD_AUTH}"

extraEnvs:
  - name: NODE_NAME
    valueFrom:
      fieldRef:
        fieldPath: spec.nodeName
