---
apiVersion: v1
kind: ConfigMap
metadata:
  name: metricbeat-init-config
  namespace: elastic-monitoring
  labels:
    k8s-app: metricbeat-init
data:
  metricbeat.yml: |-
    setup.template.settings:
      index.mapping.total_fields.limit: 10000

    metricbeat.modules:
      - module: nginx
      - module: kubernetes
      - module: docker
      - module: system
      - module: mysql
      - module: prometheus

    output.elasticsearch:
      hosts: [ "https://observability-es-http:9200" ]
      ssl.certificate_authorities:
        - /etc/elasticsearch/certificates/ca.crt
      username: "elastic"
      password: "${ES_PASSWORD}"

    setup.kibana:
      host: "https://observability-kb-http:5601"
      ssl.certificate_authorities:
        - /etc/kibana/certificates/ca.crt
      username: "elastic"
      password: "${ES_PASSWORD}"
---
apiVersion: batch/v1
kind: Job
metadata:
  name: metricbeat-init
  namespace: elastic-monitoring
spec:
  template:
    spec:
      containers:
      - name: metricbeat-init
        image: docker.elastic.co/beats/metricbeat:7.9.1
        args: [
          "-c", "/etc/metricbeat.yml",
          "-e",
          "setup"
        ]
        env:
        - name: ES_PASSWORD
          valueFrom:
            secretKeyRef:
              key: elastic
              name: observability-es-elastic-user
        resources:
          limits:
            memory: 200Mi
          requests:
            cpu: 100m
            memory: 100Mi
        securityContext:
          runAsUser: 0
        volumeMounts:
        - name: config
          mountPath: /etc/metricbeat.yml
          readOnly: true
          subPath: metricbeat.yml
        - name: cert-ca
          mountPath: "/etc/elasticsearch/certificates"
          readOnly: true
        - name: cert-ca-kb
          mountPath: "/etc/kibana/certificates"
          readOnly: true
      volumes:
      - name: config
        configMap:
          defaultMode: 0600
          name: metricbeat-init-config
      - name: cert-ca
        secret:
          secretName: observability-es-http-certs-public
      - name: cert-ca-kb
        secret:
          secretName: observability-kb-http-certs-public
      restartPolicy: Never
  backoffLimit: 0
