daemonset:
  hostNetwork: true
  extraEnvs:
    - name: LOGGING_ELASTIC_CLOUD_ID
      valueFrom:
        secretKeyRef:
          name: logging-cloud-secret
          key: cloud-id
    - name: LOGGING_ELASTIC_CLOUD_AUTH
      valueFrom:
        secretKeyRef:
          name: logging-cloud-secret
          key: cloud-auth
    - name: LOGGING_ELASTIC_CLOUD_UUID
      valueFrom:
        secretKeyRef:
          name: logging-cloud-secret
          key: cluster-uuid
  metricbeatConfig:
    metricbeat.yml: |
      setup.template.settings:
        index.mapping.total_fields.limit: 10000

      metricbeat.autodiscover:
        providers:
         - type: kubernetes
           host: ${NODE_NAME}
           hints.enabled: true

      processors:
        - add_cloud_metadata:
        - add_host_metadata:
        - add_kubernetes_metadata:
        - add_docker_metadata:

      output.logstash:
        hosts: [ "proxy-logstash.elastic-monitoring.svc.cluster.local:5044" ]

      metricbeat.modules:
      - module: system
        period: 10s
        metricsets:
          - cpu
          - load
          - memory
          - network
          - process
          - process_summary
          - core
          - diskio
          # - socket
        processes: ['.*']
        process.include_top_n:
          by_cpu: 5      # include top 5 processes by CPU
          by_memory: 5   # include top 5 processes by memory

      - module: system
        period: 1m
        metricsets:
          - filesystem
          - fsstat
        processors:
          - drop_event:
              when:
                regexp:
                  system.filesystem.mount_point: '^/(sys|cgroup|proc|dev|etc|host|lib)($|/)'

      - module: kubernetes
        metricsets:
          - node
          - system
          - pod
          - container
          - volume
        period: 10s
        host: "${NODE_NAME}"
        hosts: ["https://${NODE_NAME}:10250"]
        bearer_token_file: /var/run/secrets/kubernetes.io/serviceaccount/token
        ssl.verification_mode: "none"
        add_metadata: true

      - module: kubernetes
        enabled: true
        metricsets:
          - proxy
        hosts: ["localhost:10249"]
        period: 10s

      - module: docker
        metricsets:
          - "container"
          - "cpu"
          - "diskio"
          - "event"
          - "healthcheck"
          - "info"
          - "image"
          - "memory"
          - "network"
        hosts: ["unix:///var/run/docker.sock"]
        period: 10s
        enabled: true

      logging.level: warning

      monitoring:
        enabled: true
        cluster_uuid: "${LOGGING_ELASTIC_CLOUD_UUID}"
        cloud.id: "${LOGGING_ELASTIC_CLOUD_ID}"
        cloud.auth: "${LOGGING_ELASTIC_CLOUD_AUTH}"

clusterRoleRules:
- apiGroups: [""]
  resources:
  - nodes
  - namespaces
  - events
  - pods
  verbs: ["get", "list", "watch"]
- apiGroups: ["extensions"]
  resources:
  - replicasets
  verbs: ["get", "list", "watch"]
- apiGroups: ["apps"]
  resources:
  - statefulsets
  - deployments
  - replicasets
  verbs: ["get", "list", "watch"]
- apiGroups:
  - ""
  resources:
  - nodes/stats
  verbs:
  - get
- nonResourceURLs:
  - /metrics
  verbs:
  - get

deployment:
  extraEnvs:
    - name: LOGGING_ELASTIC_CLOUD_ID
      valueFrom:
        secretKeyRef:
          name: logging-cloud-secret
          key: cloud-id
    - name: LOGGING_ELASTIC_CLOUD_AUTH
      valueFrom:
        secretKeyRef:
          name: logging-cloud-secret
          key: cloud-auth
    - name: LOGGING_ELASTIC_CLOUD_UUID
      valueFrom:
        secretKeyRef:
          name: logging-cloud-secret
          key: cluster-uuid
  metricbeatConfig:
      metricbeat.yml: |
        setup.template.settings:
          index.mapping.total_fields.limit: 10000

        processors:
          - add_cloud_metadata:
          - drop_fields:
              when:
                equals:
                  kubernetes.service.cluster_ip: "None"
              fields: [ "kubernetes.service.cluster_ip" ]
              ignore_missing: true

        output.logstash:
          hosts: ["proxy-logstash.elastic-monitoring.svc.cluster.local:5044"]

        metricbeat.modules:

          # Needs to be disabled explicitly
        - module: system
          enabled: false

        - module: kubernetes
          enabled: true
          metricsets:
          - state_node
          - state_deployment
          - state_replicaset
          - state_statefulset
          - state_pod
          - state_container
          - state_cronjob
          - state_resourcequota
          - state_service
          - state_persistentvolume
          - state_persistentvolumeclaim
          - state_storageclass
          - event
          period: 30s
          hosts: ["${KUBE_STATE_METRICS_HOSTS}"]
          add_metadata: true

        - module: kubernetes
          enabled: true
          metricsets:
            - apiserver
          hosts: ["https://${KUBERNETES_SERVICE_HOST}:${KUBERNETES_SERVICE_PORT}"]
          ssl.verification_mode: "none"
          bearer_token_file: /var/run/secrets/kubernetes.io/serviceaccount/token
          ssl.certificate_authorities:
            - /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
          period: 10s

        logging.level: warning

        monitoring:
          enabled: true
          cluster_uuid: "${LOGGING_ELASTIC_CLOUD_UUID}"
          cloud.id: "${LOGGING_ELASTIC_CLOUD_ID}"
          cloud.auth: "${LOGGING_ELASTIC_CLOUD_AUTH}"
