daemonset:
  enabled: false

kube_state_metrics:
  enabled: false

deployment:
  extraEnvs:
    - name: LOGGING_ELASTIC_CLOUD_ID
      valueFrom:
        secretKeyRef:
          name: logging-cloud-secret
          key: cloud-id
    - name: LOGGING_ELASTIC_CLOUD_AUTH
      valueFrom:
        secretKeyRef:
          name: logging-cloud-secret
          key: cloud-auth
  metricbeatConfig:
      metricbeat.yml: |

        cloud.id: ${LOGGING_ELASTIC_CLOUD_ID}
        cloud.auth: ${LOGGING_ELASTIC_CLOUD_AUTH}

        logging.level: warning

        metricbeat.modules:

        - module: system
          enabled: false

        - module: logstash
          enabled: true
          period: 10s
          hosts: [ "proxy-logstash-headless:9600" ]
          xpack.enabled: true
